### ISSUE TITLE
chap5_CNN 的一些建议

### ISSUE THREAD

**Issue by shazhongcheng** [nndl/exercise#12]
* [x]  在tutorial_mnist_conv-keras-sequential.ipynb 这个给定的样例中，我发现 如果最后一个全连接层的激活函数如果为 tanh的话，无法得到像 样例中那样的稳定收敛的结果，是否当初没写好？

这是我的[代码](https://github.com/shazhongcheng/machine_learing_study/tree/master/%E5%A4%8D%E6%97%A6-%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E4%B8%8E%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/finished/chap4_%20simple%20neural%20network)

**Comment by jingjing-gong** [comment]
这里是有点问题，这里应该用softmax activation，多谢提醒，回头加上

**Comment by shazhongcheng** [comment]
> 这里是有点问题，这里应该用softmax activation，多谢提醒，回头加上

大神，可以告诉我 numpy 简单神经网络的答案吗？或者帮我debug一下，我写了 然后不收敛，从精度从10%到20%+ 然后回到9.8%并稳定，不知道为什么。

非常感谢！
这是我的[代码](https://github.com/shazhongcheng/machine_learing_study/blob/master/%E5%A4%8D%E6%97%A6-%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E4%B8%8E%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/finished/chap4_%20simple%20neural%20network/tutorial_minst_fnn-numpy-exercise.ipynb)

**Comment by jingjing-gong** [comment]
@shazhongcheng 你邮件ping我一下，我邮箱发给你

**Comment by shazhongcheng** [comment]
> @shazhongcheng 你邮件ping我一下，我邮箱发给你

谢谢 我邮箱是 3066078467@qq.com
