### ISSUE TITLE
关于numpy教程中softmax的前向反向传播的简化，原代码存在上溢下溢问题，反向传播过程还可进一步简化

### ISSUE THREAD

**Issue by Schizophreni** [nndl/exercise#14]
1. 原代码中softmax没有进行上溢下溢处理，即减掉每一行最大值再计算
2. 关于softmax反向传播，由于原代码中没有上溢下溢处理，可能导致exp爆炸，学习率稍大一点无法训练。关于softmax反向传播，可先对softmax取对数再用对数化的函数对输入求导。
以下是我推导后得到的代码，注释中为原来的代码（需要利用exp的值），并且需要进行matrix乘法
简化后的代码，只需要利用softmax的输出即可，简化了内存和计算量
s = self.mem['out']
        """
        sisj = np.matmul(np.expand_dims(s,axis=2), np.expand_dims(s, axis=1)) # (N, c, c)
        g_y_exp = np.expand_dims(grad_y, axis=1)
        tmp = np.matmul(g_y_exp, sisj) #(N, 1, c)
        tmp = np.squeeze(tmp, axis=1)
        tmp = -tmp+grad_y*s 
        """
        tmp = np.multiply(grad_y, s)
        grad_x = tmp - np.multiply(s, np.sum(tmp, axis=-1, keepdims=True))
        return grad_x
理论结果如下：x为输入， s=softmax(x), l为loss
![CodeCogsEqn](https://user-images.githubusercontent.com/33128518/71306030-61634e80-2416-11ea-8493-c3bd0e596649.gif)

**Comment by jingjing-gong** [comment]
是的，你有空可以提交一个pull request。我回头merge一下

**Comment by Schizophreni** [comment]
感谢大大回复，我待会儿提交一个pull request
