### ISSUE TITLE
chap_1 warmup 练习题中的一些错误与建议 （2019年8月29日）

### ISSUE THREAD

**Issue by artpli** [nndl/exercise#8]
- [ ]  语句问题： 第7题 第一句话表达不清晰，建议改为“把第5题的数组a的最后两行所有元素放到c中”
- [ ] 建议错误： 第7题 提示应该改为“a[1:3,:]”
- [ ] 错词：第10题 “从新” 应该为 “重新”
- [ ] 答案不严谨：第11题 答案应该为"int 32 或者 int 64"
- [ ] 错词：第12题 “数据类洗净” 应该为 “数据类型”
- [ ] 多逗号：第16、17、18题 “中的”后面的逗号建议删去
- [ ] 中英括号混用：第19题 第（2）问中有一个中文括号最好改为英文括号
- [ ] 提示错误：第23题 axis这个参数应该在argmax()的参数里面
- [ ] markdown问题：第23题的答题栏 应该改为code格式，而不是markdown格式
- [ ] 描述顺序：第24题 “y=x*x, x = np.arange(0, 100, 0.1) ” 建议将x和y的顺序调整一下

**Comment by shazhongcheng** [comment]
* [ ] 补充一个奇怪的地方，附加题的 最后一个 print(0.3 == 3***0.1)，是不是 print(0.3 == 3**0.1)？Python3应该没有 ***这个运算表达式吧？
* [ ] 另外，第16题和17题，除了用np的函数，直接使用 / 和 **1/2，也是没问题的
* [ ] 第11题 ，我运算结果显示为 int32，不知道和答案不同的原因为何？
暂时就这样，感谢这套课程的老师和制作人员！

**Comment by jingjing-gong** [comment]
已悉数更正，多谢指正。
