### ISSUE TITLE
chap2_linear_regression 的一些建议

### ISSUE THREAD

**Issue by shazhongcheng** [nndl/exercise#9]
* [x] 按照书中的最小二乘法公式貌似有点问题，下面是我感觉合理的公式写法
$$w^{*}=(x^{T}*x)*(x^{T}*y)$$

另外，梯度下降法的第二个多项式，我试了好多中方法都无法比较好的收敛，求大神指点

这是我的[git作业答案](https://github.com/shazhongcheng/machine_learing_study/tree/master/%E5%A4%8D%E6%97%A6-%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E4%B8%8E%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/finished)

**Comment by jingjing-gong** [comment]
一般文献上对向量描述是列向量而实际计算机用行向量表示要更高效，这跟cache有些关系，所以实现跟文献表示刚好是反的。回头我在Readme里面说明下。

**Comment by jingjing-gong** [comment]
关于polynomial feature 用GD不好收敛也是正常的。只能说这种feature对于当前任务不是很适用。
